site_name: SBC - Microchip AT91SAM9G20
site_url: https://vd-rd.github.io/sbc_at91sam9g20
repo_url: https://github.com/vd-rd/sbc_at91sam9g20
repo_name: vd-rd/sbc_at91sam9g20
theme:
  name: material
  palette:
    primary: lime
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.indexes
plugins: 
  - search

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Hardware: 
    - hardware.md
    - Build your own: hardware-ref/build-your-own.md
    - Introduction: hardware-ref/introduction.md
    - Schematics: hardware-ref/schematics.md
    - PCB: hardware-ref/pcb.md
    - BOM: hardware-ref/bom.md
    - Components: hardware-ref/components.md 
  - Software: 
    - software.md
    - Compile from source: software-ref/compile-from-source.md
    - Introduction: software-ref/introduction.md